; 屏蔽数字按键
; #If, WinActive("ahk_exe vcxsrv.exe")
; Left::NumpadLeft
; Right::NumpadRight
; Up::NumpadUp
; Down::NumpadDown
; #If
; NumpadLeft::Return
; NumpadRight::Return
; NumpadUp::Return
; NumpadDown::Return
; Numpad0::Return
; Numpad1::Return
; Numpad2::Return
; Numpad3::Return
; Numpad4::Return
; Numpad5::Return
; Numpad6::Return
; Numpad7::Return
; Numpad8::Return
; Numpad9::Return